services:
  db:
    container_name: apps_trabalho_final-mysql
    restart: always
    image: bitnami/mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=university
      - MYSQL_DATABASE=sistemademensagem
    volumes:
      - db_data:/bitnami/mysql/data
    networks:
      - app-networks

  redis:
    container_name: apps_trabalho_final-redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=university
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - app-networks

  rabbitmq:
    container_name: apps_trabalho_final-rabbitmq
    image: bitnami/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
    networks:
      - app-networks

  node-api:
    container_name: apps_trabalho_final-node
    build:
      context: ./node-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
    - ./node-api/.env
    networks:
      - app-networks

  python-api:
    container_name: apps_trabalho_final-python
    build:
      context: ./python-api
    ports:
      - "5000:5000"
    depends_on:
      - node-api
      - redis
    env_file:
      - ./python-api/.env
    networks:
      - app-networks
 

  php-api:
    container_name: apps_trabalho_final-php
    build:
      context: ./php-api
    depends_on:
      - redis
    env_file:
    - ./php-api/.env
    environment:
      JWT_SECRET: dsadjaskdhasdkjhsakjdhsae7qw89e7123ejksdajasudio
      REDIS_HOST: apps_trabalho_final-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: university
    working_dir: /var/www/html
    command: ["php", "-S", "0.0.0.0:8000", "-t", "."]
    ports:
      - "8000:8000"
    networks:
      - app-networks

volumes:
  db_data:
  redis_data:
  rabbitmq_data:

networks:
  app-networks:
    driver: bridge
