services:
  db:
    container_name: apps_trabalho_final-mysql
    restart: always
    image: bitnami/mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=university
      - MYSQL_DATABASE=sistemademensagem
    volumes:
      - db_data:/bitnami/mysql/data
    networks:
      - app-networks

  redis:
    container_name: apps_trabalho_final-redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=university
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "REDIS_PASSWORD:university", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  rabbitmq:
    container_name: apps_trabalho_final-rabbitmq
    image: bitnami/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-api:
    container_name: apps_trabalho_final-node
    build:
      context: ./node-api
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    env_file:
    - ./node-api/.env
    networks:
      - app-networks

  python-api:
    container_name: apps_trabalho_final-python
    build:
      context: ./python-api
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      node-api:
        condition: service_started
    env_file:
      - ./python-api/.env
    networks:
      - app-networks
 
  php-api:
    container_name: apps_trabalho_final-php
    build:
      context: ./php-api
    ports:
      - "7000:8000"
    depends_on:
      redis:
        condition: service_healthy
      node-api:
        condition: service_started
      python-api:
        condition: service_started
    env_file:
      - ./php-api/.env
    networks:
      - app-networks

volumes:
  db_data:
  redis_data:
  rabbitmq_data:

networks:
  app-networks:
    driver: bridge
